### ISSUE TITLE
Change the method so that it does not throw

### ISSUE THREAD

**Issue by lpatiny** [mljs/conrec#12]
The library should not throw for the timeout in order to be able to display partial results.

If the timeout is reached it could return an object like:

```
{
  result: {},
  warning: 'Timeout reached',
}
```

This is of course a breaking change.

**Comment by targos** [comment]
I would prefer `{ contours: {}, timeout: true/false }`

**Comment by targos** [comment]
Fixed by https://github.com/mljs/conrec/pull/13
