### ISSUE TITLE
Change types for input variables

### ISSUE THREAD

**Issue by lpatiny** [mljs/conrec#16]
This should be done after TS migration.
- https://github.com/mljs/conrec/issues/15

The input variables should be changes:
- number[] -> cheminfo-types NumberArray
- number[][] -> cheminfo-types NumberMatrix

And some testcases should be added with typed array to be sure we don't have a problem with fixed length array.

**Comment by wadjih-bencheikh18** [comment]
this issue is implemented in the migration https://github.com/mljs/conrec/pull/17
we just need to changes types in test

**Comment by targos** [comment]
> we just need to changes types in test

The important thing in tests is to have a few of them that use typed arrays (Float64Array) to check that the library works with them.

**Comment by wadjih-bencheikh18** [comment]
> use typed arrays (Float64Array) to check that the library works with them.

I can work on it
