### ISSUE TITLE
Project configuration

### ISSUE THREAD

**Issue by lpatiny** [mljs/conrec#25]
@targos 

Because our actions are evolving with the version of NodeJS I had to remove in the settings I had to manually edit the branch protection rules (replace 16 by 22).

Is there a way to avoid this manual edition in the future ?

<img width="728" alt="image" src="https://github.com/user-attachments/assets/73380b4d-58c8-4ad7-82ae-e5c80fbe16da">

**Comment by targos** [comment]
I'm not aware of any way
